# Generated by Django 2.0.3 on 2018-06-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='codigo',
            field=models.CharField(default='None Code', max_length=50),
        ),
        migrations.AlterField(
            model_name='codigo',
            name='celular',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
